name: benchmark-upload

on:
  workflow_run:
    workflows:
      - benchmark
    types:
      - completed

jobs:
  bencher-upload:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    permissions:
      # Allow bencher-run to write to the PR comments
      pull-requests: write
      # Allow bencher-run to read the benchmark results artifact
      actions: read
      # Allow bencher-run to write to the checks api
      checks: write
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/bencher-run
        with:
          BENCHER_API_TOKEN: ${{ secrets.BENCHER_API_TOKEN }}
          project: 238e7993-fc7a-4a69-aa82-470abd249c8b
